contigua: 
    gcc -c pilha_contigua.c -o pilha_contigua.o
    gcc main.c pilha_contigua.o -o main
    ./main
cadeada:
    gcc -c pilha_encadeada.c -o pilha_encadeada.o
    gcc main.c pilha_encadeada.o -o main
    ./main