contigua:	
	gcc -c fila-contigua.c -o fila-contigua.o
	gcc main.c fila-contigua.o -o main
	./main
	
encadeada:
	gcc -c fila-encadeada.c -o fila-encadeada.o
	gcc main.c fila-encadeada.o -o main
	./main

clean:
	rm *.o
	rm main